// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import CharactersFilterController from "./characters_filter_controller";
application.register("characters-filter", CharactersFilterController);

import CharactersTableController from "./characters_table_controller";
application.register("characters-table", CharactersTableController);

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)
